# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
after_failure:
  - |
    cd tests
    export NOT_CRAN=true
    Rscript ../.travis.R
    sleep 2
