# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false
cache: packages
env:
  global:
    - NOT_CRAN=true
    - _R_CHECK_FORCE_SUGGESTS_=false
script:
  - R CMD build .
  - travis_wait 30 R CMD check --no-build-vignettes --no-manual cloudml*tar.gz
