# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false
cache: packages
script:
  - |
    export NOT_CRAN=true
    R CMD build .
    travis_wait 30 R CMD check --no-build-vignettes --no-manual cloudml*tar.gz
after_failure:
  - |
    cd tests
    export NOT_CRAN=true
    travis_wait 30 Rscript ../.travis.R
    sleep 2
